services:
  postgres:
    image: postgres:latest
    container_name: blaze-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: caua123
      POSTGRES_DB: blazesystem
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
